### ISSUE TITLE
Can interact with Connector in the middle of a transaction

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#39] opened 2024-04-05 13:46 UTC
When I can click on the `Transfer` button, the wallet pops up, and then I'm able to click on the `Increment` button, which goes into a hung state until the transfer is complete with the wallet.

Some additional exploration showed that I could also `Get coins` and `Disconnect` the wallet while it's waiting to finalize the transaction.

Expected behaviour should be that the buttons on the page are disabled until the transaction is complete (or rejected).

https://github.com/FuelLabs/fuel-connectors/assets/114662397/9efb6aea-707c-4cf8-b02b-377d51d6a378

**Comment by luizstacio** [comment] 2024-04-23 18:00
@HoTandy We should evaluate if this is a issue only on this application or if is also true for other applications.
For the dev working on fixing this issue, also evaluate, if can be fixed on the application level, see if the problem is just application flow, or if the 2 txs are really been sent.

**Comment by HoTandy** [comment] 2024-04-30 16:16
I've only just seen the comment from @luizstacio above, sorry about that.

Checking the block explorer, and the transaction history, it only looks like the `Transfer` is approved and not the `Increment` from the `Counter Contract`.

**Closed** 2024-05-31 23:30 UTC
Labels: bug, todo
